sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm

language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install flake8 ddt unittest2 renderspec requests six
script:
  - flake8 renderspec tests/
  - python -m unittest discover tests/
